// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBStMIpbZJlV0liLB3gNkrCXeu9kWjl4HQ',
    appId: '1:839017200171:web:b17d20d8af018e667c486e',
    messagingSenderId: '839017200171',
    projectId: 'stepbystep-71192',
    authDomain: 'stepbystep-71192.firebaseapp.com',
    storageBucket: 'stepbystep-71192.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3UQ7saCNqBA7gI_idob2N9w6OmGvtwt8',
    appId: '1:839017200171:android:5d2483ee5a4b0e037c486e',
    messagingSenderId: '839017200171',
    projectId: 'stepbystep-71192',
    storageBucket: 'stepbystep-71192.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNLWiBTntWKiI3uTZitkh9O-WesMZHTKA',
    appId: '1:839017200171:ios:25dfc6b33c996dde7c486e',
    messagingSenderId: '839017200171',
    projectId: 'stepbystep-71192',
    storageBucket: 'stepbystep-71192.firebasestorage.app',
    iosClientId: '839017200171-n7nc9dsqnbrsq4fra5p9b75g97ifjvp7.apps.googleusercontent.com',
    iosBundleId: 'com.example.stepByStepApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNLWiBTntWKiI3uTZitkh9O-WesMZHTKA',
    appId: '1:839017200171:ios:25dfc6b33c996dde7c486e',
    messagingSenderId: '839017200171',
    projectId: 'stepbystep-71192',
    storageBucket: 'stepbystep-71192.firebasestorage.app',
    iosClientId: '839017200171-n7nc9dsqnbrsq4fra5p9b75g97ifjvp7.apps.googleusercontent.com',
    iosBundleId: 'com.example.stepByStepApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBStMIpbZJlV0liLB3gNkrCXeu9kWjl4HQ',
    appId: '1:839017200171:web:8da5899ee4e10b447c486e',
    messagingSenderId: '839017200171',
    projectId: 'stepbystep-71192',
    authDomain: 'stepbystep-71192.firebaseapp.com',
    storageBucket: 'stepbystep-71192.firebasestorage.app',
  );
}
